name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm install
      - name: Typecheck
        run: pnpm tsc --noEmit
      - name: Run unit tests
        run: pnpm test -- --run
      - name: Run Playwright UI tests
        run: pnpm test:ui --reporter=list
